import Salon from '../models/salon';
import { logger } from '../libs/logger';

// ─────────────────────────────────────────────────────────────────────────────
// Datos de demostración: 50 salones ficticios distribuidos en los 18
// departamentos de Mendoza. Generados para desarrollo/testing.
//
// - Las imágenes usan picsum.photos con seed fijo: cada salón muestra siempre
//   la misma foto. Para usar una foto real, basta reemplazar la URL.
// - precios_config respeta el formato de calcularMontoAlquiler
//   (fin_semana_pct / feriado_pct, por_hora, tramos_horarios, montos fijos).
// - Se insertan con findOrCreate por nombre: correr el seed varias veces
//   NO duplica salones.
// ─────────────────────────────────────────────────────────────────────────────

interface SalonDemo {
    nombre: string;
    domicilio: string;
    departamento: string;
    localidad: string;
    provincia: string;
    tipo_salon: string;
    servicios_incluidos: string;
    tipos_evento: string;
    imagen: string;
    aforo: number;
    precio_alquiler: number;
    latitud: number;
    longitud: number;
    precios_config: string | null;
}

export const SALONES_DEMO: SalonDemo[] = [
    { nombre: "Salón Los Aromos", domicilio: "Paso de los Andes 2009", departamento: "Ciudad de Mendoza", localidad: "Ciudad", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Iluminación LED\",\"Música\",\"Sillas y mesas\",\"Luces\",\"Sonido profesional\",\"Banquete\"]", tipos_evento: "[\"Gala\",\"Cumpleaños\",\"Cumpleaños de 15\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-1/800/600", aforo: 230, precio_alquiler: 1252000, latitud: -32.868825, longitud: -68.841127, precios_config: null },
    { nombre: "Espacio Aconcagua", domicilio: "Terrada 3750", departamento: "Ciudad de Mendoza", localidad: "Bombal", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Seguridad\",\"Decoración\",\"Bar\",\"Proyector\",\"Fotografía\"]", tipos_evento: "[\"Bautismos\",\"Graduación\",\"Bodas\",\"Cumpleaños de 15\",\"Baby Shower\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-2/800/600", aforo: 310, precio_alquiler: 486000, latitud: -32.896148, longitud: -68.856657, precios_config: "{\"fin_semana\":583000,\"feriado\":656000}" },
    { nombre: "Terraza del Parque", domicilio: "San Martín 3565", departamento: "Ciudad de Mendoza", localidad: "Ciudad", provincia: 'Mendoza', tipo_salon: "Terraza", servicios_incluidos: "[\"Fotografía\",\"DJ\",\"Sonido profesional\",\"Estacionamiento\",\"Decoración\",\"Wi-Fi\",\"Bar\"]", tipos_evento: "[\"Juntada de Amigos\",\"Aniversario\",\"Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-3/800/600", aforo: 60, precio_alquiler: 860000, latitud: -32.898388, longitud: -68.831038, precios_config: "{\"fin_semana\":1032000,\"feriado\":1161000}" },
    { nombre: "Quincho Don Facundo", domicilio: "Juan B. Justo 1548", departamento: "Ciudad de Mendoza", localidad: "Quinta Sección", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Escenario\",\"Estacionamiento\",\"Catering\",\"Fotografía\",\"DJ\",\"Bar\",\"Iluminación LED\",\"Luces\"]", tipos_evento: "[\"Fogata\",\"Juntada de Amigos\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-4/800/600", aforo: 50, precio_alquiler: 325000, latitud: -32.88571, longitud: -68.825016, precios_config: null },
    { nombre: "Finca La Escondida", domicilio: "Ruta Provincial 92 1198", departamento: "Godoy Cruz", localidad: "Las Tortugas", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Luces\",\"DJ\",\"Decoración\",\"Bar\",\"Estacionamiento\",\"Banquete\",\"Restaurant\"]", tipos_evento: "[\"Bodas\",\"Aniversario\",\"Gala\",\"Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-5/800/600", aforo: 350, precio_alquiler: 1832000, latitud: -32.9331, longitud: -68.880999, precios_config: null },
    { nombre: "Bodega Viña del Sol", domicilio: "Mitre 2934", departamento: "Godoy Cruz", localidad: "Las Tortugas", provincia: 'Mendoza', tipo_salon: "Bodega", servicios_incluidos: "[\"Decoración\",\"Restaurant\",\"Wi-Fi\",\"Estacionamiento\"]", tipos_evento: "[\"Degustación\",\"Gala\",\"Cóctel\",\"Negocios\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-6/800/600", aforo: 40, precio_alquiler: 1482000, latitud: -32.936891, longitud: -68.865661, precios_config: null },
    { nombre: "Salón Cristal", domicilio: "Carril Rodríguez Peña 607", departamento: "Godoy Cruz", localidad: "Godoy Cruz Centro", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Seguridad\",\"Restaurant\",\"Fotografía\",\"DJ\"]", tipos_evento: "[\"Bodas\",\"Bautismos\",\"Cumpleaños de 15\",\"Baby Shower\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-7/800/600", aforo: 200, precio_alquiler: 1554000, latitud: -32.936842, longitud: -68.841729, precios_config: null },
    { nombre: "Quinta Los Nogales", domicilio: "Maza 2752", departamento: "Godoy Cruz", localidad: "Presidente Sarmiento", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Bar\",\"Sillas y mesas\",\"DJ\",\"Proyector\",\"Catering\"]", tipos_evento: "[\"Aniversario\",\"Bodas\",\"Juntada Familiar\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-8/800/600", aforo: 170, precio_alquiler: 1305000, latitud: -32.909001, longitud: -68.85452, precios_config: "{\"fin_semana_pct\":10,\"feriado_pct\":30}" },
    { nombre: "Pelotero Mundo Feliz", domicilio: "Rivadavia 774", departamento: "Guaymallén", localidad: "Rodeo de la Cruz", provincia: 'Mendoza', tipo_salon: "Pelotero", servicios_incluidos: "[\"Seguridad\",\"Fotografía\",\"Luces\",\"Sillas y mesas\",\"Aire acondicionado\",\"Decoración\"]", tipos_evento: "[\"Baby Shower\",\"Bautismos\",\"Juntada Familiar\",\"Cumpleaños\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-9/800/600", aforo: 40, precio_alquiler: 303000, latitud: -32.879056, longitud: -68.766656, precios_config: "{\"por_hora\":true,\"precio_hora\":51000,\"precio_hora_fin_semana\":61000}" },
    { nombre: "Salón Portal de los Andes", domicilio: "Pueyrredón 2051", departamento: "Guaymallén", localidad: "Villa Nueva", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Bar\",\"Música\",\"Proyector\",\"Fotografía\",\"DJ\",\"Restaurant\",\"Banquete\",\"Decoración\"]", tipos_evento: "[\"Cumpleaños\",\"Cumpleaños de 15\",\"Baby Shower\",\"Aniversario\",\"Graduación\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-10/800/600", aforo: 330, precio_alquiler: 1020000, latitud: -32.911819, longitud: -68.770652, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":612000},{\"horas\":5,\"precio\":867000},{\"horas\":8,\"precio\":1020000}],\"fin_semana_pct\":10}" },
    { nombre: "Quincho El Algarrobo", domicilio: "Aristóbulo del Valle 4217", departamento: "Guaymallén", localidad: "Villa Nueva", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Proyector\",\"Iluminación LED\",\"Bar\",\"Wi-Fi\",\"Sillas y mesas\",\"Seguridad\",\"Estacionamiento\"]", tipos_evento: "[\"Fogata\",\"Juntada de Amigos\",\"Aniversario\",\"Juntada Familiar\",\"Cumpleaños\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-11/800/600", aforo: 90, precio_alquiler: 289000, latitud: -32.915222, longitud: -68.806665, precios_config: "{\"por_hora\":true,\"precio_hora\":36000,\"precio_hora_fin_semana\":43000}" },
    { nombre: "Terraza Mirador Oeste", domicilio: "Maza 4201", departamento: "Guaymallén", localidad: "San José", provincia: 'Mendoza', tipo_salon: "Terraza", servicios_incluidos: "[\"Sillas y mesas\",\"Wi-Fi\",\"Fotografía\",\"Música\"]", tipos_evento: "[\"Juntada de Amigos\",\"Sunset\",\"Cumpleaños\",\"Aniversario\",\"Cóctel\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-12/800/600", aforo: 110, precio_alquiler: 374000, latitud: -32.895495, longitud: -68.803737, precios_config: "{\"fin_semana_pct\":10,\"feriado_pct\":30}" },
    { nombre: "Finca Santa Elena", domicilio: "Perú 1695", departamento: "Las Heras", localidad: "El Challao", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Restaurant\",\"Decoración\",\"Escenario\",\"Estacionamiento\",\"Aire acondicionado\"]", tipos_evento: "[\"Sunset\",\"Gala\",\"Degustación y Sunset\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-13/800/600", aforo: 180, precio_alquiler: 777000, latitud: -32.833013, longitud: -68.880712, precios_config: null },
    { nombre: "Bodega Piedra Negra", domicilio: "Sarmiento 3983", departamento: "Las Heras", localidad: "Panquehua", provincia: 'Mendoza', tipo_salon: "Bodega", servicios_incluidos: "[\"Bar\",\"Fotografía\",\"Escenario\",\"Iluminación LED\",\"Wi-Fi\",\"Banquete\",\"DJ\"]", tipos_evento: "[\"Cóctel\",\"Bodas\",\"Gala\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-14/800/600", aforo: 140, precio_alquiler: 927000, latitud: -32.867108, longitud: -68.851125, precios_config: "{\"fin_semana_pct\":15,\"feriado_pct\":25}" },
    { nombre: "Salón Emperador", domicilio: "Rivadavia 801", departamento: "Las Heras", localidad: "Panquehua", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Seguridad\",\"Sillas y mesas\",\"Wi-Fi\",\"Restaurant\",\"DJ\"]", tipos_evento: "[\"Cumpleaños\",\"Cumpleaños de 15\",\"Aniversario\",\"Bodas\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-15/800/600", aforo: 390, precio_alquiler: 1067000, latitud: -32.83607, longitud: -68.893466, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":640000},{\"horas\":5,\"precio\":907000},{\"horas\":8,\"precio\":1067000}],\"fin_semana_pct\":10}" },
    { nombre: "Quinta El Retiro", domicilio: "Alem 3977", departamento: "Las Heras", localidad: "Ciudad de Las Heras", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Iluminación LED\",\"Luces\",\"Escenario\",\"Aire acondicionado\",\"Sonido profesional\",\"Seguridad\",\"Estacionamiento\"]", tipos_evento: "[\"Aniversario\",\"Cumpleaños de 15\",\"Baby Shower\",\"Sunset\",\"Juntada Familiar\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-16/800/600", aforo: 390, precio_alquiler: 1209000, latitud: -32.871195, longitud: -68.859991, precios_config: null },
    { nombre: "Pelotero Saltamontes", domicilio: "Terrada 3495", departamento: "Luján de Cuyo", localidad: "Agrelo", provincia: 'Mendoza', tipo_salon: "Pelotero", servicios_incluidos: "[\"Restaurant\",\"Luces\",\"Wi-Fi\",\"Catering\",\"Fotografía\",\"Sonido profesional\"]", tipos_evento: "[\"Juntada Familiar\",\"Bautismos\",\"Baby Shower\",\"Cumpleaños\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-17/800/600", aforo: 60, precio_alquiler: 231000, latitud: -33.050148, longitud: -68.871177, precios_config: null },
    { nombre: "Salón Jardines del Este", domicilio: "Lavalle 3554", departamento: "Luján de Cuyo", localidad: "Agrelo", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Decoración\",\"Sonido profesional\",\"Seguridad\",\"Bar\"]", tipos_evento: "[\"Cumpleaños\",\"Aniversario\",\"Gala\",\"Bautismos\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-18/800/600", aforo: 430, precio_alquiler: 1311000, latitud: -33.023028, longitud: -68.868698, precios_config: "{\"fin_semana\":1573000,\"feriado\":1770000}" },
    { nombre: "Quincho La Tranquera", domicilio: "España 2576", departamento: "Luján de Cuyo", localidad: "Agrelo", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Bar\",\"Sillas y mesas\",\"Sonido profesional\",\"Música\",\"Fotografía\",\"Banquete\",\"Aire acondicionado\"]", tipos_evento: "[\"Fogata\",\"Juntada Familiar\",\"Cumpleaños\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-19/800/600", aforo: 40, precio_alquiler: 410000, latitud: -33.033188, longitud: -68.898219, precios_config: "{\"fin_semana\":492000,\"feriado\":554000}" },
    { nombre: "Finca Los Olivos", domicilio: "Patricias Mendocinas 1592", departamento: "Luján de Cuyo", localidad: "Carrodilla", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Escenario\",\"Fotografía\",\"DJ\",\"Estacionamiento\",\"Catering\",\"Decoración\",\"Aire acondicionado\"]", tipos_evento: "[\"Aniversario\",\"Degustación y Sunset\",\"Bodas\",\"Gala\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-20/800/600", aforo: 210, precio_alquiler: 983000, latitud: -33.048299, longitud: -68.853228, precios_config: null },
    { nombre: "Salón Alameda", domicilio: "Videla Aranda 4318", departamento: "Luján de Cuyo", localidad: "Carrodilla", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Luces\",\"Restaurant\",\"Decoración\",\"Aire acondicionado\",\"Seguridad\",\"Estacionamiento\",\"Wi-Fi\"]", tipos_evento: "[\"Bautismos\",\"Graduación\",\"Baby Shower\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-21/800/600", aforo: 320, precio_alquiler: 918000, latitud: -33.016053, longitud: -68.882326, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":551000},{\"horas\":5,\"precio\":780000},{\"horas\":8,\"precio\":918000}],\"fin_semana_pct\":10}" },
    { nombre: "Terraza Cielo Cuyano", domicilio: "Emilio Civit 3399", departamento: "Maipú", localidad: "Luzuriaga", provincia: 'Mendoza', tipo_salon: "Terraza", servicios_incluidos: "[\"Iluminación LED\",\"Seguridad\",\"Música\",\"DJ\",\"Fotografía\",\"Luces\",\"Aire acondicionado\"]", tipos_evento: "[\"Aniversario\",\"Juntada de Amigos\",\"Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-22/800/600", aforo: 180, precio_alquiler: 427000, latitud: -32.987265, longitud: -68.802113, precios_config: null },
    { nombre: "Bodega Antigua Toscana", domicilio: "Aristóbulo del Valle 1258", departamento: "Maipú", localidad: "Russell", provincia: 'Mendoza', tipo_salon: "Bodega", servicios_incluidos: "[\"Aire acondicionado\",\"Fotografía\",\"Sillas y mesas\",\"Catering\",\"Wi-Fi\",\"Iluminación LED\",\"Música\",\"Restaurant\"]", tipos_evento: "[\"Degustación\",\"Bodas\",\"Negocios\",\"Gala\",\"Degustación y Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-23/800/600", aforo: 160, precio_alquiler: 630000, latitud: -32.99028, longitud: -68.782183, precios_config: null },
    { nombre: "Salón Diamante", domicilio: "Juan B. Justo 1836", departamento: "Maipú", localidad: "Coquimbito", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Banquete\",\"Proyector\",\"Bar\",\"Sillas y mesas\",\"Estacionamiento\",\"Sonido profesional\",\"Wi-Fi\",\"Fotografía\"]", tipos_evento: "[\"Bautismos\",\"Cumpleaños\",\"Baby Shower\",\"Cumpleaños de 15\",\"Bodas\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-24/800/600", aforo: 210, precio_alquiler: 1371000, latitud: -32.998732, longitud: -68.815605, precios_config: "{\"fin_semana\":1645000,\"feriado\":1851000}" },
    { nombre: "Quinta Las Acacias", domicilio: "Perú 2160", departamento: "Maipú", localidad: "Coquimbito", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Música\",\"Iluminación LED\",\"Banquete\",\"Decoración\",\"Wi-Fi\",\"Catering\",\"Proyector\"]", tipos_evento: "[\"Baby Shower\",\"Juntada Familiar\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-25/800/600", aforo: 330, precio_alquiler: 973000, latitud: -33.000983, longitud: -68.78879, precios_config: null },
    { nombre: "Quincho El Fogón", domicilio: "Boulogne Sur Mer 416", departamento: "Maipú", localidad: "Luzuriaga", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Catering\",\"Música\",\"Seguridad\",\"Sonido profesional\",\"Sillas y mesas\"]", tipos_evento: "[\"Fogata\",\"Aniversario\",\"Cumpleaños\",\"Juntada Familiar\",\"Juntada de Amigos\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-26/800/600", aforo: 100, precio_alquiler: 166000, latitud: -32.988902, longitud: -68.801226, precios_config: null },
    { nombre: "Salón Vendimia", domicilio: "Perú 1212", departamento: "San Martín", localidad: "Palmira", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Banquete\",\"DJ\",\"Fotografía\",\"Aire acondicionado\",\"Sonido profesional\",\"Sillas y mesas\"]", tipos_evento: "[\"Cumpleaños\",\"Cumpleaños de 15\",\"Baby Shower\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-27/800/600", aforo: 410, precio_alquiler: 1407000, latitud: -33.075182, longitud: -68.446426, precios_config: "{\"por_hora\":true,\"precio_hora\":201000,\"precio_hora_fin_semana\":241000}" },
    { nombre: "Finca Valle Andino", domicilio: "España 4000", departamento: "San Martín", localidad: "Palmira", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Seguridad\",\"Restaurant\",\"Música\",\"Wi-Fi\",\"Luces\"]", tipos_evento: "[\"Bodas\",\"Sunset\",\"Degustación y Sunset\",\"Aniversario\",\"Gala\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-28/800/600", aforo: 140, precio_alquiler: 551000, latitud: -33.080139, longitud: -68.487625, precios_config: "{\"fin_semana_pct\":25,\"feriado_pct\":20}" },
    { nombre: "Pelotero Arcoíris", domicilio: "Ruta Provincial 15 4373", departamento: "San Martín", localidad: "Ciudad de San Martín", provincia: 'Mendoza', tipo_salon: "Pelotero", servicios_incluidos: "[\"Escenario\",\"Luces\",\"Iluminación LED\",\"Banquete\"]", tipos_evento: "[\"Juntada Familiar\",\"Cumpleaños\",\"Baby Shower\",\"Bautismos\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-29/800/600", aforo: 60, precio_alquiler: 288000, latitud: -33.073132, longitud: -68.487574, precios_config: "{\"fin_semana_pct\":10,\"feriado_pct\":30}" },
    { nombre: "Salón del Sauce", domicilio: "Ozamis 1501", departamento: "Rivadavia", localidad: "La Central", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Sonido profesional\",\"Restaurant\",\"Escenario\",\"Proyector\",\"Estacionamiento\"]", tipos_evento: "[\"Baby Shower\",\"Cumpleaños\",\"Graduación\",\"Bautismos\",\"Bodas\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-30/800/600", aforo: 120, precio_alquiler: 1424000, latitud: -33.165801, longitud: -68.444558, precios_config: null },
    { nombre: "Quincho Los Parrales", domicilio: "Adolfo Calle 2611", departamento: "Rivadavia", localidad: "Ciudad de Rivadavia", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Wi-Fi\",\"Proyector\",\"DJ\",\"Sillas y mesas\"]", tipos_evento: "[\"Aniversario\",\"Juntada de Amigos\",\"Fogata\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-31/800/600", aforo: 40, precio_alquiler: 332000, latitud: -33.184734, longitud: -68.450492, precios_config: null },
    { nombre: "Terraza La Cúpula", domicilio: "Ozamis 1182", departamento: "Junín", localidad: "Ciudad de Junín", provincia: 'Mendoza', tipo_salon: "Terraza", servicios_incluidos: "[\"Sonido profesional\",\"Escenario\",\"Iluminación LED\",\"Proyector\",\"DJ\"]", tipos_evento: "[\"Juntada de Amigos\",\"Cumpleaños\",\"Cóctel\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-32/800/600", aforo: 130, precio_alquiler: 824000, latitud: -33.120733, longitud: -68.483517, precios_config: null },
    { nombre: "Bodega Camino del Vino", domicilio: "Carril Rodríguez Peña 458", departamento: "Junín", localidad: "La Colonia", provincia: 'Mendoza', tipo_salon: "Bodega", servicios_incluidos: "[\"Seguridad\",\"Catering\",\"Luces\",\"Estacionamiento\",\"Proyector\",\"Wi-Fi\"]", tipos_evento: "[\"Bodas\",\"Gala\",\"Degustación\",\"Degustación y Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-33/800/600", aforo: 200, precio_alquiler: 1693000, latitud: -33.124479, longitud: -68.501152, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":1016000},{\"horas\":5,\"precio\":1439000},{\"horas\":8,\"precio\":1693000}],\"fin_semana_pct\":10}" },
    { nombre: "Salón Real Maipú", domicilio: "Bandera de los Andes 2054", departamento: "Tunuyán", localidad: "Los Sauces", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Aire acondicionado\",\"DJ\",\"Sillas y mesas\",\"Decoración\",\"Luces\",\"Fotografía\"]", tipos_evento: "[\"Bodas\",\"Graduación\",\"Baby Shower\",\"Cumpleaños de 15\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-34/800/600", aforo: 360, precio_alquiler: 687000, latitud: -33.592291, longitud: -69.013873, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":412000},{\"horas\":5,\"precio\":584000},{\"horas\":8,\"precio\":687000}],\"fin_semana_pct\":10}" },
    { nombre: "Quinta San Cayetano", domicilio: "Las Heras 1145", departamento: "Tunuyán", localidad: "Los Sauces", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Estacionamiento\",\"Decoración\",\"Sillas y mesas\",\"Wi-Fi\",\"Bar\"]", tipos_evento: "[\"Cumpleaños de 15\",\"Bodas\",\"Baby Shower\",\"Juntada Familiar\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-35/800/600", aforo: 330, precio_alquiler: 1155000, latitud: -33.565314, longitud: -69.01109, precios_config: "{\"por_hora\":true,\"precio_hora\":165000,\"precio_hora_fin_semana\":198000}" },
    { nombre: "Salón Estación Palmira", domicilio: "Ruta Provincial 92 1669", departamento: "Tunuyán", localidad: "Los Sauces", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Música\",\"Sonido profesional\",\"Aire acondicionado\",\"Decoración\",\"Bar\",\"Seguridad\",\"Escenario\",\"Sillas y mesas\"]", tipos_evento: "[\"Bodas\",\"Gala\",\"Aniversario\",\"Baby Shower\",\"Bautismos\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-36/800/600", aforo: 250, precio_alquiler: 1588000, latitud: -33.576489, longitud: -69.000056, precios_config: null },
    { nombre: "Quincho La Rueda", domicilio: "Ruta Provincial 15 893", departamento: "Tupungato", localidad: "Ciudad de Tupungato", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Restaurant\",\"Aire acondicionado\",\"Bar\",\"Escenario\",\"Seguridad\",\"Fotografía\",\"Luces\"]", tipos_evento: "[\"Aniversario\",\"Fogata\",\"Cumpleaños\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-37/800/600", aforo: 30, precio_alquiler: 407000, latitud: -33.352834, longitud: -69.167043, precios_config: null },
    { nombre: "Finca Tierra Nuestra", domicilio: "Ruta Provincial 92 3784", departamento: "Tupungato", localidad: "San José", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Aire acondicionado\",\"Iluminación LED\",\"DJ\",\"Catering\",\"Decoración\"]", tipos_evento: "[\"Bodas\",\"Aniversario\",\"Gala\",\"Degustación y Sunset\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-38/800/600", aforo: 240, precio_alquiler: 1602000, latitud: -33.361894, longitud: -69.159409, precios_config: "{\"fin_semana_pct\":20,\"feriado_pct\":20}" },
    { nombre: "Salón Del Este Eventos", domicilio: "España 1024", departamento: "San Carlos", localidad: "La Consulta", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Bar\",\"Sonido profesional\",\"Wi-Fi\",\"Sillas y mesas\",\"Luces\",\"Banquete\",\"Estacionamiento\",\"Restaurant\"]", tipos_evento: "[\"Bautismos\",\"Baby Shower\",\"Graduación\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-39/800/600", aforo: 430, precio_alquiler: 1513000, latitud: -33.794164, longitud: -69.036057, precios_config: "{\"por_hora\":true,\"precio_hora\":216000,\"precio_hora_fin_semana\":259000}" },
    { nombre: "Quinta La Amistad", domicilio: "Alem 2155", departamento: "San Carlos", localidad: "Eugenio Bustos", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Sillas y mesas\",\"Bar\",\"Iluminación LED\",\"Fotografía\"]", tipos_evento: "[\"Baby Shower\",\"Bodas\",\"Sunset\",\"Cumpleaños de 15\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-40/800/600", aforo: 140, precio_alquiler: 729000, latitud: -33.784272, longitud: -69.011917, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":437000},{\"horas\":5,\"precio\":620000},{\"horas\":8,\"precio\":729000}],\"fin_semana_pct\":10}" },
    { nombre: "Salón Manzano Histórico", domicilio: "Belgrano 3275", departamento: "San Rafael", localidad: "Rama Caída", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Bar\",\"Sillas y mesas\",\"Proyector\",\"Estacionamiento\"]", tipos_evento: "[\"Cumpleaños de 15\",\"Aniversario\",\"Graduación\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-41/800/600", aforo: 400, precio_alquiler: 442000, latitud: -34.638031, longitud: -68.317522, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":265000},{\"horas\":5,\"precio\":376000},{\"horas\":8,\"precio\":442000}],\"fin_semana_pct\":10}" },
    { nombre: "Finca Viento Sur", domicilio: "Sarmiento 1298", departamento: "San Rafael", localidad: "Cuadro Nacional", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Sonido profesional\",\"Estacionamiento\",\"Proyector\",\"Seguridad\",\"Fotografía\"]", tipos_evento: "[\"Sunset\",\"Bodas\",\"Gala\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-42/800/600", aforo: 190, precio_alquiler: 1039000, latitud: -34.624847, longitud: -68.316559, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":623000},{\"horas\":5,\"precio\":883000},{\"horas\":8,\"precio\":1039000}],\"fin_semana_pct\":15}" },
    { nombre: "Bodega Alto Tupungato", domicilio: "Sarmiento 2460", departamento: "San Rafael", localidad: "Ciudad de San Rafael", provincia: 'Mendoza', tipo_salon: "Bodega", servicios_incluidos: "[\"Estacionamiento\",\"Aire acondicionado\",\"Música\",\"Sillas y mesas\",\"Sonido profesional\",\"Escenario\",\"Catering\",\"Banquete\"]", tipos_evento: "[\"Degustación y Sunset\",\"Cóctel\",\"Negocios\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-43/800/600", aforo: 120, precio_alquiler: 2058000, latitud: -34.596992, longitud: -68.312122, precios_config: "{\"fin_semana_pct\":15,\"feriado_pct\":30}" },
    { nombre: "Quincho Cordillera", domicilio: "Rivadavia 4176", departamento: "General Alvear", localidad: "Bowen", provincia: 'Mendoza', tipo_salon: "Quincho", servicios_incluidos: "[\"Wi-Fi\",\"Estacionamiento\",\"Sonido profesional\",\"Sillas y mesas\"]", tipos_evento: "[\"Cumpleaños\",\"Aniversario\",\"Juntada de Amigos\",\"Fogata\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-44/800/600", aforo: 90, precio_alquiler: 150000, latitud: -34.974381, longitud: -67.706267, precios_config: "{\"fin_semana\":180000,\"feriado\":203000}" },
    { nombre: "Salón Uco Eventos", domicilio: "Azcuénaga 1769", departamento: "General Alvear", localidad: "Bowen", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Escenario\",\"Banquete\",\"Restaurant\",\"Aire acondicionado\",\"Seguridad\",\"DJ\",\"Proyector\"]", tipos_evento: "[\"Cumpleaños\",\"Cumpleaños de 15\",\"Aniversario\",\"Graduación\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-45/800/600", aforo: 410, precio_alquiler: 681000, latitud: -34.956221, longitud: -67.700752, precios_config: null },
    { nombre: "Finca El Cerrito", domicilio: "Patricias Mendocinas 191", departamento: "Malargüe", localidad: "Ciudad de Malargüe", provincia: 'Mendoza', tipo_salon: "Finca", servicios_incluidos: "[\"Música\",\"Aire acondicionado\",\"Seguridad\",\"Iluminación LED\",\"Luces\",\"Estacionamiento\",\"Restaurant\"]", tipos_evento: "[\"Aniversario\",\"Sunset\",\"Degustación y Sunset\",\"Bodas\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-46/800/600", aforo: 310, precio_alquiler: 954000, latitud: -35.47424, longitud: -69.565686, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":572000},{\"horas\":5,\"precio\":811000},{\"horas\":8,\"precio\":954000}],\"fin_semana_pct\":15}" },
    { nombre: "Salón Diamante del Sur", domicilio: "Ozamis 707", departamento: "Malargüe", localidad: "Ciudad de Malargüe", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Restaurant\",\"Decoración\",\"Proyector\",\"Fotografía\",\"DJ\"]", tipos_evento: "[\"Cumpleaños de 15\",\"Aniversario\",\"Baby Shower\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-47/800/600", aforo: 170, precio_alquiler: 1434000, latitud: -35.474806, longitud: -69.57237, precios_config: "{\"fin_semana\":1721000,\"feriado\":1936000}" },
    { nombre: "Quinta Los Álamos", domicilio: "España 4713", departamento: "Lavalle", localidad: "Villa Tulumaya", provincia: 'Mendoza', tipo_salon: "Quinta", servicios_incluidos: "[\"Luces\",\"Iluminación LED\",\"Aire acondicionado\",\"DJ\",\"Fotografía\",\"Seguridad\",\"Banquete\",\"Escenario\"]", tipos_evento: "[\"Baby Shower\",\"Juntada Familiar\",\"Aniversario\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-48/800/600", aforo: 400, precio_alquiler: 1129000, latitud: -32.728609, longitud: -68.568654, precios_config: null },
    { nombre: "Terraza Río Diamante", domicilio: "Belgrano 4029", departamento: "Santa Rosa", localidad: "Villa Santa Rosa", provincia: 'Mendoza', tipo_salon: "Terraza", servicios_incluidos: "[\"Iluminación LED\",\"Sonido profesional\",\"Seguridad\",\"Bar\"]", tipos_evento: "[\"Cóctel\",\"Sunset\",\"Juntada de Amigos\",\"Cumpleaños\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-49/800/600", aforo: 90, precio_alquiler: 724000, latitud: -33.259613, longitud: -68.128322, precios_config: null },
    { nombre: "Salón Alvear Centro", domicilio: "Mitre 2682", departamento: "La Paz", localidad: "Villa La Paz", provincia: 'Mendoza', tipo_salon: "Salón", servicios_incluidos: "[\"Aire acondicionado\",\"Luces\",\"Decoración\",\"Sillas y mesas\",\"DJ\",\"Fotografía\"]", tipos_evento: "[\"Bautismos\",\"Cumpleaños de 15\",\"Bodas\"]", imagen: "https://picsum.photos/seed/dreamevents-salon-50/800/600", aforo: 410, precio_alquiler: 1121000, latitud: -33.449533, longitud: -67.569011, precios_config: "{\"tramos_horarios\":[{\"horas\":3,\"precio\":673000},{\"horas\":5,\"precio\":953000},{\"horas\":8,\"precio\":1121000}],\"fin_semana_pct\":10}" },
];

export const seedSalones = async (): Promise<void> => {
    let creados = 0;
    for (const data of SALONES_DEMO) {
        const [, created] = await Salon.findOrCreate({
            where: { nombre: data.nombre },
            defaults: { ...data, dueno_id: null },
        });
        if (created) creados++;
    }
    logger.info(`[Seed] Salones demo: ${creados} creados, ${SALONES_DEMO.length - creados} ya existían`);
};
