ALTER TABLE personas 
MODIFY COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
SELECT * FROM personas;
DELETE FROM personas where id_persona=3;
ALTER TABLE PERSONAS
MODIFY COLUMN email VARCHAR(40) NOT NULL UNIQUE;


use CEM;
ALTER TABLE Roles ADD COLUMN descripcion VARCHAR(255) NULL;

ALTER TABLE Personas ADD COLUMN google_id VARCHAR(255) NULL